### ISSUE TITLE
Suggestion: get rid of lodash

### ISSUE THREAD

**Issue by cmajsmith** [jwarby/i18n-lint#10]
Just a suggestion. I checked a code and the only method used from lodash is `.last()`. So may be it can be changed to a simple js `array[length - 1]` like lodash does itself: https://github.com/lodash/lodash/blob/master/last.js ?

**Comment by jwarby** [comment]
Yep it's a bit overkill to pull in the whole library just for that :laughing: feel free to submit a PR for this one too :)

**Comment by CmajSmith** [comment]
Great! Will do both accepted asap.
