### ISSUE TITLE
Package i18n-lint no longer available

### ISSUE THREAD

**Issue by Platonn** [jwarby/i18n-lint#14]
Hi @jwarby! The tool `jwarby/i18n-lint` has recently disappeared from npm. Is it a temporary issue or `i18n-lint` is no longer maintained?

![image](https://user-images.githubusercontent.com/4001059/65030514-fb12ef80-d93f-11e9-9fc2-a3b373797b3c.png)

**Comment by jwarby** [comment]
Hi @Platonn, it was never actually published to npm. `npm install jwarby/i18n-lint` is still working fine for me (npm v6.11.3), alternatively you could try with `npm install github:jwarby/i18n-lint` if it's not working for you.

**Comment by jwarby** [comment]
Package is now available on npm.

**Comment by Platonn** [comment]
@jwarby my bad. Anyway, thank you for publishing it on NPM 😉
